<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="light" nsURI="http://occiware.org/light/ecore" nsPrefix="light">
  <eClassifiers xsi:type="ecore:EClass" name="Light" eSuperTypes="platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//Resource">
    <eAnnotations source="OCCIE2Ecore">
      <details key="title"/>
    </eAnnotations>
    <eOperations name="switchOn">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title" value="Turn on the light"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="switchOff">
      <eAnnotations source="OCCIE2Ecore">
        <details key="title" value="Turn off the light"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType platform:/plugin/org.occiware.clouddesigner.occi/model/OCCI.ecore#//String"
        defaultValueLiteral="off">
      <eAnnotations source="OCCIE2Ecore">
        <details key="description" value="Light IOT Resource"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
